# This workflow will do a clean installation of node dependencies,
# cache/restore them, compile the source code, run tests and then generate and publish badges

name: Test Branch Man CI

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      DISPLAY: ":99.0"

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Node.js dependencies
        run: npm ci

      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v3

      - name: Prepare tests
        run: npm run pretest

      - name: Run tests (headless)
        run: npm run test:coverage

      - name: Move coverage summary
        run: npm run move-coverage

      - name: Create Badges
        run: npm run make-badges

      - name: Deploy badges
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./badges
